// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArcKdN9NJbyxohRYHXJ2ISbOArmCk8hTc',
    appId: '1:979793251511:web:777fc2200e5dc9195f9132',
    messagingSenderId: '979793251511',
    projectId: 'signuppage-e00cb',
    authDomain: 'signuppage-e00cb.firebaseapp.com',
    storageBucket: 'signuppage-e00cb.appspot.com',
    measurementId: 'G-M2Z4HYN6KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrz4PctnbbXoKi5PmPoVoGBaGzeAhpL1Y',
    appId: '1:979793251511:android:0ec7b4b6d217929c5f9132',
    messagingSenderId: '979793251511',
    projectId: 'signuppage-e00cb',
    storageBucket: 'signuppage-e00cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD96Ku2PeW-UwW7c6qFnYJTjHGRCwsTmOM',
    appId: '1:979793251511:ios:5323a666f563b8545f9132',
    messagingSenderId: '979793251511',
    projectId: 'signuppage-e00cb',
    storageBucket: 'signuppage-e00cb.appspot.com',
    iosClientId: '979793251511-5rubhrf3cl26t5ntkf13focm9os6v3il.apps.googleusercontent.com',
    iosBundleId: 'com.example.signUpPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD96Ku2PeW-UwW7c6qFnYJTjHGRCwsTmOM',
    appId: '1:979793251511:ios:62ae6c2ac237792e5f9132',
    messagingSenderId: '979793251511',
    projectId: 'signuppage-e00cb',
    storageBucket: 'signuppage-e00cb.appspot.com',
    iosClientId: '979793251511-efbl0ngooaj5jv3sg0vsv2018askhel6.apps.googleusercontent.com',
    iosBundleId: 'com.example.signUpPage.RunnerTests',
  );
}
